apiVersion: apps/v1
kind: Deployment
metadata:
  name: mission-deployment
  labels:
    app: mission
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mission
  template:
    metadata:
      labels:
        app: mission
    spec:
      containers:
      - name: mission
        image: shubhz1452/mission:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mission-service
spec:
  selector:
    app: mission
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
